---
title: Bibliometrics analysis and text mining to reduce the burden of systematic article selection in a literature review
author: Aly Lamuri
---

Objectives: With the exponential growth of scientific publications, systematically searching across the breadth of a topic becomes a challenge. Specifically in health technology assessment, providing an ordered set of analyzed policy options would also mean assessing, comparing, and reviewing numerous published literature. Reproducibility of the literature review is essential to ensure that the recommendation is drawn from a just conclusion. This research showcases bibliometrics analysis and text mining as an initial step in conducting a systematically reproducible literature review on psychological resilience.

Methods: Scientific articles on psychological resilience were retrieved from the Web of Science, Scopus, Medline, and Cochrane databases. All data were exported as text files and standardized using the Web of Science core collection field tags. The data is deduplicated and cleaned upon merging to nullify redundant retrievals and ensure data field consistency. Stop-word removal and n-gram tokenization were performed on the abstract to acquire unigram, bigram, and trigram tokens. Document-frequency matrices were then constructed by pairing the tokens to their digital object identifiers. Structural topic models were fitted on each n-gram token and then evaluated by scoring the semantic coherence and exclusivity. The most probable topic and keywords per document were drawn from the best-performing model and augmented to the data frame. Descriptive bibliometrics analyses were performed on the whole dataset, and inferential couplings were assessed only on entries retrieved from the Web of Science. A subset of data is used for bibliographic coupling analysis due to its metadata completeness, where the Web of Science entries had the most complete entries.

Results: From 50 years of research on psychological resilience, 33,584 unique articles were extracted. There was a 3.97% annual growth rate and over 1 million cross-citations involving almost 100,000 co-authors across 5,000 distinct sources of publications. Three topic models were extracted for each unigram, bigram, and trigram token, resulting in 11, 10, and 17 identified topics. Topics on post-traumatic symptoms have persisted as a major theme in resilience research for half a century. Meanwhile, topics on depressive symptoms emerge as a theme of interest in early 2000. Grouping by the thematic clusters, 50 articles were extracted for further review.

Discussion: The change in research themes becomes apparent upon conducting bibliometrics analyses. A streamlined method of systematic search is paramount to providing justifiable policy recommendations. Bibliometrics analysis combined with text mining is viable to conduct a thorough and reproducible literature review.
